# AARRR Pirate Metrics Framework - Layer 7
# Business alignment through funnel metrics

version: "1.0"
source: "Dave McClure's Pirate Metrics"

# ===== THE FRAMEWORK =====
stages:
  acquisition:
    name: "Acquisition"
    question: "How do users find us?"
    goal: "Attract potential users to the product"
    channels:
      - organic_search
      - paid_ads
      - referral
      - social_media
      - content_marketing
      - partnerships
    key_metrics:
      - name: "Traffic by channel"
        type: count
      - name: "Cost per acquisition (CPA)"
        type: currency
      - name: "Click-through rate (CTR)"
        type: percentage
    journeys:
      - landing_page_view
      - marketing_funnel_entry

  activation:
    name: "Activation"
    question: "Do users have a great first experience?"
    goal: "Users experience core value quickly"
    key_moments:
      - signup_complete
      - first_value_experience
      - aha_moment
    key_metrics:
      - name: "Signup rate"
        type: percentage
        formula: "signups / visitors"
      - name: "Activation rate"
        type: percentage
        formula: "activated / signups"
      - name: "Time to first value"
        type: duration
    journeys:
      - onboarding
      - first_use

  retention:
    name: "Retention"
    question: "Do users come back?"
    goal: "Users return and continue using product"
    time_frames:
      - day_1
      - day_7
      - day_30
      - day_90
    key_metrics:
      - name: "D1/D7/D30 retention"
        type: percentage
      - name: "Churn rate"
        type: percentage
      - name: "Session frequency"
        type: count
    journeys:
      - return_visit
      - habit_formation

  revenue:
    name: "Revenue"
    question: "Do users pay?"
    goal: "Convert to paying customers"
    monetization_events:
      - trial_to_paid
      - upgrade
      - renewal
    key_metrics:
      - name: "Conversion rate"
        type: percentage
      - name: "Average revenue per user (ARPU)"
        type: currency
      - name: "Customer lifetime value (LTV)"
        type: currency
      - name: "Monthly recurring revenue (MRR)"
        type: currency
    journeys:
      - payment_flow
      - upgrade_flow

  referral:
    name: "Referral"
    question: "Do users tell others?"
    goal: "Users actively recommend product"
    referral_mechanisms:
      - invite_system
      - share_features
      - testimonials
    key_metrics:
      - name: "Net Promoter Score (NPS)"
        type: score
      - name: "Referral rate"
        type: percentage
        formula: "referrals / active_users"
      - name: "Viral coefficient (K-factor)"
        type: ratio
    journeys:
      - invite_flow
      - share_flow

# ===== JOURNEY → AARRR MAPPING =====
journey_mapping:
  # Map each journey to its primary AARRR stage
  template:
    journey_id: "journey-name"
    aarrr_stage: "activation"
    metrics:
      - metric_name: "value"
      - metric_name: "value"

# ===== TRACKING SETUP =====
tracking:
  events:
    acquisition:
      - page_view
      - utm_capture
    activation:
      - signup
      - first_action
      - aha_moment
    retention:
      - session_start
      - feature_use
    revenue:
      - checkout_start
      - payment_complete
    referral:
      - share_click
      - invite_sent
      - invite_accepted
